controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

excel_compare:
    path: /compare-excel-files
    controller: 'App\Controller\CompareExcelFilesController::compare'
    methods: ['POST']
